name: 安徽科技日报

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:

      - name: 拉取代码
        uses: actions/checkout@v4


      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: 安装依赖
        run: |
          pip install openai requests


      - name: 生成日报
        run: python main.py
        env:
          DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
